---
resources:
- name: first-concourse-pipeline
  type: git
  source:
    uri: https://github.com/afournier-pivotal/concourse
jobs:
- name: hello-world-job
  plan:
   - task: hello-world-task
     file: concourse/tasks/hello-world/hello-world-task.yml
